### ISSUE TITLE
考虑默认使用匿名GPT

### ISSUE THREAD

**Issue by NewFuture** [chenxizhang/openai-powershell#223]
现在ChatGPT已经可以不登录匿名使用了，可以实现开箱即用，不用必须配置`API_KEY`。

这样体验会上一个数量级😄

**Comment by chenxizhang** [comment]
> 现在ChatGPT已经可以不登录匿名使用了，可以实现开箱即用，不用必须配置`API_KEY`。
> 
> 这样体验会上一个数量级😄

API访问 他们还是要钱的，要key的 🤣，现在是允许匿名访问 chatgpt.com 这个网页，但也只是能用 gpt3.5
